"""add world engine tables

Revision ID: b1a455fce69a
Revises: 2ed56e69af35
Create Date: 2026-06-19 02:11:19.091852
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1a455fce69a'
down_revision = '2ed56e69af35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worlds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('premise', sa.Text(), nullable=False),
    sa.Column('world_contract', sa.Text(), nullable=False),
    sa.Column('visual_contract', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worlds_project_id'), 'worlds', ['project_id'], unique=False)
    op.create_table('world_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('created_event', sa.String(length=50), nullable=True),
    sa.Column('updated_event', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_entities_world_id'), 'world_entities', ['world_id'], unique=False)
    op.create_table('world_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('turn', sa.Integer(), nullable=False),
    sa.Column('action_kind', sa.String(length=20), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=False),
    sa.Column('outcome_summary', sa.Text(), nullable=False),
    sa.Column('time_advance_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_events_world_id'), 'world_events', ['world_id'], unique=False)
    op.create_table('world_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('from_entity_id', sa.Integer(), nullable=False),
    sa.Column('to_entity_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('valid_from_event', sa.String(length=50), nullable=False),
    sa.Column('valid_until_event', sa.String(length=50), nullable=True),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_entity_id'], ['world_entities.id'], ),
    sa.ForeignKeyConstraint(['to_entity_id'], ['world_entities.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_edges_world_id'), 'world_edges', ['world_id'], unique=False)
    op.create_table('world_state_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('owner_entity_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('updated_event', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_entity_id'], ['world_entities.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_state_slots_world_id'), 'world_state_slots', ['world_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_world_state_slots_world_id'), table_name='world_state_slots')
    op.drop_table('world_state_slots')
    op.drop_index(op.f('ix_world_edges_world_id'), table_name='world_edges')
    op.drop_table('world_edges')
    op.drop_index(op.f('ix_world_events_world_id'), table_name='world_events')
    op.drop_table('world_events')
    op.drop_index(op.f('ix_world_entities_world_id'), table_name='world_entities')
    op.drop_table('world_entities')
    op.drop_index(op.f('ix_worlds_project_id'), table_name='worlds')
    op.drop_table('worlds')
    # ### end Alembic commands ###
